version: '3.5'

services:
  api-instance-1:
    image: rinha23:0.0.1
    container_name: api-pessoas-01
    hostname: api-pessoas-01
    restart: always
    depends_on:
      - banco-rinha
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 0.5GB

  api-instance-2:
    image: rinha23:0.0.1
    container_name: api-pessoas-02
    hostname: api-pessoas-02
    restart: always
    depends_on:
      - banco-rinha
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 0.5GB
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-instance-1
      - api-instance-2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 0.5GB

  banco-rinha:
    image: postgres:14.9
    restart: always
    volumes:
      - ./scripts/createdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1.5GB
